description: |-
  Cas de test pour QFv2 avec jeton FranceConnect.
  Les données proviennent des jetons de l'environnement de test FranceConnect.
  L'endpoint est appellé avec le jeton FranceConnect + le recipient.

params:
  prenoms:
    - 'Emmanuel'
    - 'Alexandre'
    - 'Nicolas'
  nomNaissance: "DELALALALANDE"
  anneeDateNaissance: 1991
  moisDateNaissance: 1
  jourDateNaissance: 7
  sexeEtatCivil: "M"
  codeCogInseeCommuneNaissance: "75101"
  codeCogInseePaysNaissance: "99100"
status: 200
payload: |-
  {
  "data": {
    "allocataires": [
        {
          "nom_naissance": "DELALALALANDE",
          "nom_usage": "",
          "prenoms": "EMMANUEL ALEXANDRE NICOLAS",
          "date_naissance": "1991-01-07",
          "sexe": "M"
        },
        {
          "nom_naissance": "CARPENTIER",
          "nom_usage": "DELALALALANDE",
          "prenoms": "FLORENCE",
          "date_naissance": "1990-05-30",
          "sexe": "F"
        }
      ],
      "enfants": [
        {
          "nom_naissance": "DELALALALANDE",
          "nom_usage": "",
          "prenoms": "Alex",
          "date_naissance": "2015-02-15",
          "sexe": "M"
        },
        {
          "nom_naissance": "DELALALALANDE",
          "nom_usage": "",
          "prenoms": "Léo",
          "date_naissance": "2017-02-02",
          "sexe": "M"
        },
        {
          "nom_naissance": "DELALALALANDE",
          "nom_usage": "",
          "prenoms": "Laura",
          "date_naissance": "2019-12-31",
          "sexe": "F"
        }
      ],
      "adresse": {
        "destinataire": "Monsieur et Madame Emmanuel DELALALALANDE",
        "complement_information": null,
        "complement_information_geographique": null,
        "numero_libelle_voie": "20 AVENUE DE SEGUR",
        "lieu_dit": null,
        "code_postal_ville": "75107 PARIS",
        "pays": "FRANCE"
      },
    "quotient_familial": {
          "fournisseur": "CNAF",
          "valeur": 2550,
          "annee": 2024,
          "mois": 2,
          "annee_calcul": 2024,
          "mois_calcul": 12
        }
    },
    "links": {},
    "meta": {}
  }
